### PR TITLE
Edit rules, add regex flags, modify UI a bit

### PR DESCRIPTION
**Pull request by djedi**

### CODE REVIEW

**Comment by jkingsman** [comment]
Awesome; thanks again for the interest (and much needed tidy up). 

Would you be open to posting a quick screen share of your changes going over what's modified? This is pretty sweeping; just wanna have an overview of everything that's changing. Once I've verified, I'll post the new version to the app store ^_^

**Comment by djedi** [comment]
https://www.screencast.com/t/MWeuY3kBVt7

**Comment by jkingsman** [comment]
Gorgeous!! Thank you, my friend! Merged; building a new package now.

**Comment by jkingsman** [comment]
Oops, forgot to post earlier -- new version has been up for a couple hours now.

**Pull request merged**
